version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
      
  user_app:
    build:
      network:host
      context: ./
      dockerfile: Dockerfile

environment:
  - DATABASE_URL=postgresql://postgres:mysecretpassword@postgress:5432/postgres

ports:
  -"3000:3000"
depends_on:
 - postgres